### ISSUE TITLE
Interpretation of results

### ISSUE THREAD

**Issue by MickWest1** [jbpease/dfoil#1]
Dear James,

Thank you for sharing such a useful tool. I have a couple of questions that I hope you can help with. I have successfully run the test data but cannot seem to get the pdf to plot successfully using the test2 dataset. The pdf contains the axes and the key but nothing else has been plotted. Is this normal or maybe I have done something wrong?
I have also run Dfoil using a whole genomic dataset of my own and get the same problem with the pdf. 
To try and get around this I used the dfoil_analyze.py but have no idea how to interpret my results in the context of directional gene flow which I was hoping the pdf would help with.

The input file I used is the following (the tab delineation was probably lost when pasting it)
#chrom  position        AAAAA   AAABA   AABAA   AABBA   ABAAA   ABABA   ABBAA   ABBBA   BAAAA BAABA   BABAA   BABBA   BBAAA   BBABA   BBBAA   BBBBA
combined.fa       0       860766588       721658  713518  5384224 588059  5950    10970   61250   585050  6698    5215    46745   5031516 48887   50451   21043329

I would greatly appreciate any feedback and can also send my analyze results too if that would help

Thanks,
Mick

**Comment by jbpease** [comment]
Hi Mick,

For the graph to work, you have to have several partitions.  At the moment the plot is trying to display just one point from your whole dataset.  The plots are designed for non-overlapping genomic windows arranged spatially on the chromosome, where each entry is a row in the input data file.  

James

**Comment by MickWest1** [comment]
Thank you for your reply. So these windows need to be in their own individual fasta files or is there another way to do it with your software?

**Comment by MickWest1** [comment]
Thank you for your help. I managed to get it working now I think. The pdf is a little messy but I think the analyze output should be easier to interpret. I have added my output for the introgression calls. I am guessing the first column is the order of introgression? e.g. from my data 14 1 means 1 window supported introgression from taxon 1 into taxon 4? If this is the case, what do none mean and na?
# Introgression Calls:
none 8511
14 1
23 6
na 999
41 3
123 73
124 70
32 1

Thank you for any help.
