### ISSUE TITLE
Analysis and output interpretation questions

### ISSUE THREAD

**Issue by awolfewood** [jbpease/dfoil#3]
Dear James,

If you have time, I have three questions about running dfoil. A bit of background: I am running DFOIL on a transcriptome dataset of ~700 orthologs recovered from cone snail venom ducts with the goal to detect introgression among a group of closely related species. Ideally, I’d like to analyze each ortholog as a separate window in order to get an idea of which ones are candidates for introgression.

When I run Dfoil, however, I’m running into some problems:

**1). Problem with fasta2dfoil.py.**  I start with alignments for each ortholog, and use _fasta2defoil.py_ to convert them into pattern counts for dfoil input. I use this command:

    python fasta2dfoil.py *.alignment —out OUTPUT —names taxa1,taxa2,taxa3,outgroup

This produces a pattern count file with each ortholog as a separate entry, like I want (the output file is attached: **fasta2dfoil_output**). However, all of the entries for the different patterns are zero. I don’t understand why.

I think I got around this problem by using mvftools to convert the fasta alignments into a .mvf file (_ConvertFasta2MVF_) and prepare a pattern count file (_CalcPatternCount_) to input to dfoil. This produces a pattern count file that seems to make more sense (see attached file: **mvftools_patterncount.xlsx**).

Do you have any ideas as to why _fasta2dfoil.py_ would produce all zeros when I see pattern counts that seem to make sense when I use mvftools?

**2). Understanding pattern count output file.** I want to make sure I understand the pattern count file. For each column (e.g. ABAA, ABBA) there is a number or a period. The numbers denote the number of biallelic sites in a given window that support a particular pattern, correct? And the sum of those number should equal the total number of biallelic sites detected for that window?

**3). dfoil.py output.** When I run dfoil on the pattern count file that I made with mvftools, I’m getting some weird (to me) output. With an input file that contains 708 separate windows and default _dfoil.py_ parameters, I get 4 windows in my output file. The output file is attached (**dfoil_out_default.xlsx**), and I have annotated it with what I think each column means - am I on track? (green for columns I'm pretty sure I understand, yellow for one's I don't think are that important to my issue, and red for ones that I'm not sure about).

I read through the dfoil manual to see if I could find any clues as to why so many windows get thrown out and all I could figure was that many of the windows were getting thrown out because they didn't meet the default values for --mincount (10) or --mintotal (50).  However, when I look at my pattern count file (attached: **mvftools_patterncount.xlsx**) and sum the total number of sites for each contig, there are 32 contigs with 50 sites or greater.

Do you have any ideas about why 28 of them might be getting tossed out"?

Thanks so much!

Andrew Wood

[dfoil_out_default.xlsx](https://github.com/jbpease/dfoil/files/2081218/dfoil_out_default.xlsx)
[fasta2dfoil_output.txt](https://github.com/jbpease/dfoil/files/2081219/fasta2dfoil_output.txt)
[mvftools_patterncount.xlsx](https://github.com/jbpease/dfoil/files/2081220/mvftools_patterncount.xlsx)

**Comment by jbpease** [comment]
1. Are your names in the FASTA file for each sequence `taxa1,taxa2,taxa3,outgroup` these labels have to match exactly or the script will not work.

2/3 Can you send me your exact command line for mvftools?  Your output file seems to have too many columns, but I could not replicate the problem.

**Comment by conJUSTover** [comment]
@awolfewood I had a similar problem as you with fasta2dfoil.py, and it turns out that the fasta sequence must contain capital A/T/C/G, not lowercase a/t/c/g. Maybe this can help? 

@jbpease Is this an easy fix to the script? Thanks in advance.

**Comment by jbpease** [comment]
Hi @conJUSTover and @awolfewood,

fasta2dfoil.py now should accept lower case as well, but upper-casing the strings in the script before analyzing them.

Thanks,
James
