### ISSUE TITLE
Ambiguities, questions more than issue...

### ISSUE THREAD

**Issue by joqb** [jbpease/dfoil#7]
Dear James,

How does Dfoil handle ambiguities (Y, R...)? Does it ignore them as N and "?" or does it somehow use them?
Also am I right to understand that in the case of a homoploid hybrid speciation (50/50) Dfoil would not be able to identify it? Which leads me to MVFtools, I am very interested in doing the same kind of analysis as in the biorxiv paper from Hibbins and Hahn but I do not understand how to get the different distances according to the different trees. I can see the CalcPairwiseDistances but not how to condition it to the topologies. A little help would be greatly appreciated.

Thanks,
Jonathan

**Comment by jbpease** [comment]
Hi Jonathan,

DFOIL ignores ambiguities.  The inclusion of both alleles for a single species is not tractable in the DFOIL framework.  If you suspect perfect homoploid speciation has occurred, then this would violate one of the model assumptions for DFOIL.  DFOIL requires a five-taxon symmetric tree, and a "perfect" homoploid species would violate this topology requirement.  However, if you assigned it (arbitrarily) as sister to one of the parentals in a tree, then it should detect the unexpectedly close relationship with the other "non-sister" parent.  

I do not want to give you wrong information about the Hibbins methods, in terms of their exact commands. I would recommend contacting them directly.  Feel free to cc me and I can help facilitate on the software end.

James

**Comment by joqb** [comment]
Hi James,

Thanks for your explanations. I will try to contact them shortly.

Cheers,
Jonathan
